## Información para spring-boot-starter-actuator
info:
  app:
    name: servicio-de-descubrimiento
    description: Spring Cloud Eureka PoC SERVIDOR
    version: 0.0.1-SNAPSHOT
  java-vendor:  ${java.specification.vendor}
      
## Configuring info endpoint
spring:  
  application:
    name: servicio-de-descubrimiento
#eureka:
#  client:
#    service-url:
#      defaultZone: 
---
# Para usar este perfil
# java -D"spring.profiles.active=nodo1" -jar target/EurekaServer-0.0.1-SNAPSHOT.jar
spring:
  profiles: nodo1
eureka:
  instance:
    hostname: nodo1
    metadataMap:
      zone: zona1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
server:  
  port: ${PORT:8761}
---
# Para usar este perfil
# java -D"spring.profiles.active=nodo2" -jar target/EurekaServer-0.0.1-SNAPSHOT.jar
spring:
  profiles: nodo2
eureka:
  instance:
    hostname: nodo2
    metadataMap:
      zone: zona2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
server:  
  port: ${PORT:8762}
  
---
# Para usar este perfil
# java -D"spring.profiles.active=nodo3" -jar target/EurekaServer-0.0.1-SNAPSHOT.jar
spring:
  profiles: nodo3
eureka:
  instance:
    hostname: nodo3
    metadataMap:
      zone: zona3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
server:  
  port: ${PORT:8763}
