
## Información para spring-boot-starter-actuator
info:
  app:
    name: servicio-de-gateway
    description: Spring Cloud Eureka PoC Gateway
    version: 0.0.1-SNAPSHOT
  java-vendor:  ${java.specification.vendor}
      
## Configuring info endpoint
spring:  
  application:
    name: servicio-gateway

server:
  port: ${PORT:7000} 
    
## Configuración Zuul
zuul:
  prefix: /api
  routes:
#    client:
    servicio-de-clientes:
      path: /cliente/**
      service-id: servicio-de-clientes

## Configuración Ribbon
ribbon:
  eureka:
    enabled: true

---
# Perfil zona1
# java -D"spring.profiles.active=zona1" -jar target/Gateway-0.0.1-SNAPSHOT.jar
spring:
  profiles: zona1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
server:  
  port: ${PORT:7654}

---
# Perfil zona2
# java -D"spring.profiles.active=zona2" -jar target/Gateway-0.0.1-SNAPSHOT.jar---
spring:
  profiles: zona2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
server:  
  port: ${PORT:7655}

---
# Perfil zona3
# java -D"spring.profiles.active=zona3" -jar target/Gateway-0.0.1-SNAPSHOT.jar---
spring:
  profiles: zona3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
server:  
  port: ${PORT:7656}
